seg 26 fev 2024 00:34:48 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/mkiso b/mkiso
--- a/mkiso
+++ b/mkiso
@@ -4,6 +4,7 @@
 #
 #-
 # Copyright (c) 2009-2015 Juan Romero Pardines.
+# Copyright (c) 2023-2024 Vilmar Catafesta <vcatafesta@gmail.com>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -26,12 +27,27 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #-
-
 #xbps-install -U -r /tmp/fakeroot --repository=https://repo-fastly.voidlinux.org/current bash -S
+
+#export LANGUAGE=pt_BR
+export TEXTDOMAINDIR=/usr/share/locale
+export TEXTDOMAIN=void-install
+# flag languages
+declare -gA Alanguage=([pt_BR]=0 [en_US]=1 [de_DE]=2 [fr_FR]=3 [es_ES]=4 [it_IT]=5)
+declare -gA Alocale=([0]=pt_BR [1]=en_US [2]=de_DE [3]=fr_FR [4]=es_ES [5]=it_IT)
+
 #debug
 export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
 #set -x
 #set -e
+shopt -s extglob
+
+#system
+readonly APP="${0##*/}"
+readonly _VERSION_='1.0.26-20240226'
+readonly distro=$(uname -n)
+readonly DEPENDENCIES=(rsync sed cat cp umount losetup grep chroot mkfs.vfat tee)
+
 trap 'error_out $? $LINENO' INT TERM 0
 umask 022
 declare -gi MAKE_X=0
@@ -40,15 +56,17 @@ declare -gi MAKE_XFCE_CUSTOM=0
 declare -gi MAKE_AWESOME=0
 declare -gi LBIND=0
 declare -gi QUIET=0
+readonly true=1
+readonly false=0
 declare -g title='Void Linux Custom'
 
 sh_choose_packages() {
-    print_step "Configurando pacotes essenciais"
+    print_step "Selecionando pacotes essenciais"
 	declare -a INCLUDE_DIRS=()
 	declare -g PROGNAME=$(basename "$0")
 	declare -g REQUIRED_PKGS="base-files libgcc dash coreutils sed tar gawk syslinux grub-i386-efi grub-x86_64-efi memtest86+ squashfs-tools xorriso"
 	declare -g INITRAMFS_PKGS="binutils device-mapper dhclient dracut-network openresolv"
-	declare -g ADDITIONAL_PKGS="dialog gettext curl wget git pv nano parted tree htop rsync"
+	declare -g ADDITIONAL_PKGS="dialog gettext curl wget git pv nano parted tree htop rsync lynx parallel tmate gpm"
 	ADDITIONAL_PKGS+=" grub-void-theme"
 	ADDITIONAL_PKGS+=" xz zstd porg"
 	ADDITIONAL_PKGS+=" bc geoip geoipupdate iputils lvm2 cryptsetup"
@@ -62,8 +80,8 @@ sh_choose_packages() {
 }
 
 sh_choose_packages_awesome() {
-    title='Void Linux Awesome Custom'
-    print_step "Escolhendo pacotes X Awesome Custom"
+    title='Void Linux X/Awesome Custom'
+    print_step "Selecionando pacotes X Awesome Custom"
     #xorg
     ADDITIONAL_PKGS+=" xorg xinit xterm dbus dbus-x11 elogind dbus-elogind polkit-elogind xdg-user-dirs xrdb"
     #xfce
@@ -89,8 +107,8 @@ sh_choose_packages_awesome() {
 }
 
 sh_choose_packages_xfce_base() {
-    title='Void Linux XFCE Base'
-    print_step "Escolhendo pacotes X Base"
+    title='Void Linux X/XFCE Base'
+    print_step "Selecionando pacotes XFCE Base"
     #xorg
     ADDITIONAL_PKGS+=" xorg xinit xterm dbus dbus-x11 dbus-elogind polkit-elogind xdg-user-dirs xrdb"
     #xfce
@@ -112,8 +130,8 @@ sh_choose_packages_xfce_base() {
 }
 
 sh_choose_packages_xfce_custom() {
-    title='Void Linux XFCE Custom'
-    print_step "Escolhendo pacotes X Custom"
+    title='Void Linux X/XFCE Custom'
+    print_step "Selecionando pacotes XFCE Custom"
 	ADDITIONAL_PKGS+=" xfce4-screenshooter xfce4-dict"
     ADDITIONAL_PKGS+=" xfce4-battery-plugin"
     ADDITIONAL_PKGS+=" xfce4-clipman-plugin"
@@ -160,7 +178,7 @@ sh_choose_packages_xfce_custom() {
 	ADDITIONAL_PKGS+=" bat"
 	ADDITIONAL_PKGS+=" vlc celluloid"
 	ADDITIONAL_PKGS+=" evince"
-	ADDITIONAL_PKGS+=" mate-calc cmatrix tmate xkill menulibre mugshot ocs-url"
+	ADDITIONAL_PKGS+=" mate-calc cmatrix xkill menulibre mugshot ocs-url"
 	ADDITIONAL_PKGS+=" nvme-cli"
 	ADDITIONAL_PKGS+=" inxi"
 #
@@ -191,13 +209,85 @@ sh_diahora() {
 	printf "%s\n" "$DIAHORA"
 }
 
-sh_confAmbiente() {
+sh_setEnvironment() {
 	declare -g BOOTLOG="/tmp/void-mklive-$(sh_diahora).log"
 	declare -g LOGGER='/dev/tty8'
-	declare -g STEP_COUNT=21
+	declare -gi STEP_COUNT=22
+
+    # flag languages
+    : PT_BR=0
+    : "${EN_US=1}"
+    : "${DE_DE=2}"
+    : "${FR_FR=3}"
+    : "${LC_DEFAULT=$(sh_getLocale)}"
 }
 
-sh_setvarcolors() {
+sh_setLanguage() {
+    #   langmsg=('lang=("pt_BR" "en_US" "de_DE" "fr_FR" "es_ES" "it_IT")')
+    #   for xmsg in "${langmsg[@]}"; do eval "$xmsg"; done
+    #   #echo "lang       ${#lang[@]} ${lang[@]} ${lang[$PT_BR]} ${lang[$EN_US]}"
+    #   #echo "cmsg_ERRO ${#cmsg_ERRO[@]} ${cmsg_ERRO[@]} ${cmsg_ERRO[$PT_BR]} ${cmsg_ERRO[$EN_US]}"
+
+    #   cmsg_LABEL[pt_BR]=$(gettext "Usar as teclas ${RED}↑ PARA CIMA ${RESET}e ${RED}↓ PARA BAIXO ${RESET}para navegar.\nUsar ${RED}T>
+    #   cmsg_LBL_check[pt_BR]=$(gettext "Usar as teclas ${RED}PARA CIMA ${RESET}e ${RED}PARA BAIXO ${RESET}para navegar.\nUsar ${RED}B>
+    #   cmsg_Tarball_Corrompido[pt_BR]=$(gettext "\n${RED}Aparentemente o tarball rootfs ${_TARBALL_ROOTFS} está corrompido.\n\n${BOLD>
+    cmsg_CommandNotFound[pt_BR]=$(gettext "não encontrei o comando")
+    cmsg_ImpossivelContinuar[pt_BR]=$(gettext "IMPOSSÍVEL CONTINUAR")
+    cmsg_ImpossivelContinuar1[pt_BR]=$(gettext "Esse script precisa dos comandos listados acima")
+    cmsg_ImpossivelContinuar2[pt_BR]=$(gettext "Instale-os e/ou verifique se estão no seu")
+    cmsg_InstCommand[pt_BR]=$(gettext "Instalar o(s) comando(s)")
+    cmsg_RunNew[pt_BR]=$(gettext "INFO: Rode novamente o aplicativo")
+    cmsg_RunNewErro[pt_BR]=$(gettext "ERRO na instalação dos comandos. Tente manualmente")
+}
+readconf() {
+    if [[ $LC_DEFAULT -eq 0 ]]; then
+        read -r -p "$@ [S/n]"
+    else
+        read -r -p "$@ [Y/n]"
+    fi
+    [[ ${REPLY^} == "" ]] && return $false
+    [[ ${REPLY^} == N ]] && return $true || return $false
+}
+
+sh_checkDependencies() {
+    local d
+    local errorFound=0
+    declare -a missing
+
+    for d in "${DEPENDENCIES[@]}"; do
+        [[ -z $(command -v "$d") ]] && missing+=("$d") && errorFound=1 && printf '%s\n' "${red}${cmsg_ERRO[$LC_DEFAULT]}${reset}: ${cmsg_CommandNotFound[$LC_DEFAULT]} ${cyan}'$d'${reset}"
+    done
+    if ((errorFound)); then
+        echo "${yellow}--------------${cmsg_ImpossivelContinuar[$LC_DEFAULT]}-------------${reset}"
+        echo "${cmsg_ImpossivelContinuar1[$LC_DEFAULT]}" >&2
+        echo "${cmsg_ImpossivelContinuar2[$LC_DEFAULT]} \$PATH" >&2
+        echo "${yellow}-----------------------------------------------${reset}"
+
+        if [[ "$distro" = @(void|void-live|voidlinux) ]]; then
+            echo
+            if readconf "${yellow}${cmsg_InstCommand[$LC_DEFAULT]} '${cyan}${missing[*]}${reset}' ?"; then
+                if xbps-install -Sy "${missing[@]}"; then
+                    errorFound=0
+                    sh_checkDependencies
+                else
+                    die "${cmsg_RunNewErro[$LC_DEFAULT]}"
+                fi
+            fi
+        else
+            die "${cmsg_ERRO[$LC_DEFAULT]}: ${cmsg_InstalacaoAbortada[$LC_DEFAULT]}..."
+        fi
+    fi
+}
+
+sh_setAsciiLines() {
+    if [[ "$LANG" =~ 'UTF-8' ]]; then
+        export NCURSES_NO_UTF8_ACS=0
+    else
+        export NCURSES_NO_UTF8_ACS=1
+    fi
+}
+
+sh_setVarColors() {
 	reset=$(tput sgr0)
 	# Definir os estilos de texto como variáveis
 	bold=$(tput bold)
@@ -225,6 +315,17 @@ sh_setvarcolors() {
 	light_magenta=$(tput setaf 13)
 	light_cyan=$(tput setaf 14)
 	bright_white=$(tput setaf 15)
+}
+
+sh_getLocale() {
+    local lc
+
+    LC_DEFAULT="${Alanguage[pt_BR]}"
+    LOCALE="pt_BR"
+    #   if lc=$(grep _ <(locale -a) | head -1 | cut -c1-5); then
+    #       LOCALE="$lc"
+    #       LC_DEFAULT="${Alanguage[$lc]}"
+    #   fi
 }
 
 die() {
@@ -315,7 +416,7 @@ install_prereqs() {
 }
 
 install_packages() {
-    print_step "Testando void pkgs..."
+    print_step "Running dry-run for packages list selected..."
 	{
 		LC_ALL=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -r "$ROOTFS" ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -yn $PACKAGE_LIST $INITRAMFS_PKGS $ADDITIONAL_PKGS
 	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
@@ -324,7 +425,7 @@ install_packages() {
 
 	mount_pseudofs
 
-    print_step "Instalando void pkgs BASE INITRAMFS em rootfs..."
+    print_step "Instalando pacotes void BASE INITRAMFS em $ROOTFS..."
     {
 		LC_ALL=C XBPS_ARCH=$BASE_ARCH "${XBPS_INSTALL_CMD}" -U -r "$ROOTFS" ${XBPS_REPOSITORY} -c "$XBPS_CACHEDIR" -y $PACKAGE_LIST $INITRAMFS_PKGS
 	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
@@ -366,6 +467,8 @@ get_conf_path() {
         path='config-xfce-custom'
     elif ((MAKE_AWESOME)); then
         path='config-awesome-custom'
+    else
+        path='config-base-custom'
     fi
     echo "$path"
 }
@@ -416,6 +519,15 @@ install_usr() {
 	{
 		[ -d "$ROOTFS/usr" ] && mkdir -p "$ROOTFS"/usr/
 		rsync -a $path/usr/ $ROOTFS/usr/
+	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
+}
+
+install_common() {
+    local path='config-common'
+
+	print_step "Copiando config-common into $ROOTFS/usr/"
+	{
+        rsync -a $path/ $ROOTFS/
 	} 2>&1 | tee -i -a "$BOOTLOG" >$LOGGER
 }
 
@@ -696,8 +808,12 @@ usage() {
 #
 # main()
 #
-sh_confAmbiente
-sh_setvarcolors
+sh_setVarColors
+sh_setEnvironment
+sh_getLocale
+sh_setLanguage
+sh_checkDependencies
+sh_setAsciiLines
 
 while getopts "a:b:r:c:C:T:Kk:l:i:I:S:s:o:p:g:v:VhXxYyQqWw" opt; do
 	case $opt in
@@ -839,7 +955,7 @@ sh_monitor() {
     fi
 }
 
-print_step "Synchronizing XBPS repository data..."
+print_step "Sincronizando dados do repositório XBPS..."
 {
 	copy_void_keys "$ROOTFS"
 	copy_void_keys "$VOIDHOSTDIR"
@@ -880,7 +996,7 @@ else
     : ${OUTPUT_FILE="void-live-base-custom-${BASE_ARCH}-${KERNELVERSION}-$(sh_diahora).iso"}
 fi
 
-print_step "Installing software to generate the image..."
+print_step "Instalando software para gerar a imagem de disco..."
 install_prereqs
 
 mkdir -p "$ROOTFS"/etc
@@ -892,7 +1008,7 @@ if [ -n "$IGNORE_PKGS" ]; then
 	ignore_packages
 fi
 
-print_step "Installing void pkgs into the rootfs..."
+print_step "Instalando pacotes void em $ROOTFS..."
 install_packages
 install_skel
 if ((MAKE_X)); then
@@ -904,6 +1020,7 @@ if ((MAKE_XFCE_CUSTOM)); then
     install_icons
 fi
 install_usr
+install_common
 install_chili_apps
 install_grub_themes
 reconfigure_packages
@@ -920,6 +1037,9 @@ if ((MAKE_X)); then
     	: ${ADDITIONAL_SERVICE_LIST_FULL:=avahi-daemon bluetoothd cupsd irqbalance sshd uuidd }
     	enable_services ${ADDITIONAL_SERVICE_LIST_FULL}
     fi
+else # tty
+    : ${ADDITIONAL_SERVICE_LIST_BASE:=gpm}
+    enable_services ${ADDITIONAL_SERVICE_LIST_BASE}
 fi
 
 if [ "${#INCLUDE_DIRS[@]}" -gt 0 ]; then
@@ -947,3 +1067,4 @@ generate_iso_image
 
 hsize=$(du -sh "$OUTPUT_FILE" | awk '{print $1}')
 info_msg "${green}Created $(readlink -f "$OUTPUT_FILE") ($hsize) successfully.${reset}"
+
